### ISSUE TITLE
aviatrix-role-app should only be assumed by aviatrix-role-ec2

### ISSUE THREAD

**Issue by JonasSaegesser** [AviatrixSystems/terraform-modules#2]
The assume_role_policy of the aviatrix-role-app allows everyone in the account to assume the role:
"AWS": "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"

It should be closed down, so that only the aviatrix-role-ec2 role can assume the role.

**Comment by jorgebonilla** [comment]
This is a great point. 
The purpose of this Terraform Module is to serve as  a quickstart.
For further information on customizing Aviatrix IAM roles we have documented the process here: http://docs.aviatrix.com/HowTos/customize_aws_iam_policy.html
