### ISSUE TITLE
Output the ARNs from aviatrix-controller-iam-roles

### ISSUE THREAD

**Issue by jholloway7** [AviatrixSystems/terraform-modules#56]
The module outputs the role names, but not the ARNs.  Other aviatrix resources tend to accept ARNs as input.  It's easy enough to put together the ARNs manually but seems like it would be a good approach to just output them from this module so they can be referenced elsewhere.

**Comment by inc1t3Ful** [comment]
Hello @jholloway7 ,

Thank you for bringing this to our attention! I will file a ticket for enhancement and notify the team; I will update here accordingly.

**Comment by daroga0002** [comment]
I addressed this on https://github.com/AviatrixSystems/terraform-modules/pull/72

**Comment by daroga0002** [comment]
PR was merged so @jholloway7 it should solve your issue
