### ISSUE TITLE
Format of the 'Name' tag changed for ec2 instance

### ISSUE THREAD

**Issue by piotr-dobrowolski-dragon** [AviatrixSystems/terraform-modules#68]
Hello
Latest refactor changed the format of the 'Name' tag for EC2 instance
From:
format("%s%s-%d", local.name_prefix, "AviatrixController", count.index)
To:
Name = "${local.name_prefix} AviatrixController ${count.index}"

change visible in terraform plan:
 ~ "Name"            = "AviatrixController-0" -> " AviatrixController 0"

IMO there is unnecessary white space char at the beginning of the string, value of this tag is also used here:
https://github.com/AviatrixSystems/Controller-HA-for-AWS/blob/master/aviatrix_ha.py
It's easy to make a mistake and ends up with error:

"Can't find Controller instance with name tag AviatrixController 0. list index out of range"

we are using this tag also to create lambda function but now it fails:
"Error: Error creating Lambda function: ValidationException: 1 validation error detected: Value ' AviatrixController 0-ha' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:(aws[a-zA-Z-]*)?:lambda:)?([a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?"

Can we back to old format ?

**Comment by daroga0002** [comment]
I have opened https://github.com/AviatrixSystems/terraform-modules/pull/71 to address this issue.

**Comment by daroga0002** [comment]
@piotr-dobrowolski-dragon  PR was merged so this should solve your issue
