### ISSUE TITLE
EC2 IAM Role Name conflicts

### ISSUE THREAD

**Issue by gitteri** [AviatrixSystems/terraform-modules#9]
When setting up a new aviatrix controller I had to specify the iam role for EC2 instances. Aviatrix appears to now require the role to be named exactly as "aviatrix-role-ec2", with no prefix allowed. I have a ticket open with support to see if this is necessary.

In the meantime, running this terraform module with a name_prefix does not work.

**Comment by ryanliu1021** [comment]
With current Aviatrix implementation, any AWS IAM role must be named exactly same as [Aviatrix documented](https://docs.aviatrix.com/HowTos/HowTo_IAM_role.html?#create-two-iam-roles)

**Comment by bzfxn6** [comment]
Should this really be closed?   

If you configure a parameter that is in the notes, which then breaks the configuration.  Should you not remove the parameter.  Or change the code so that it doesn't break.

**Comment by arvindsree** [comment]
We would first need the controller to support custom role names, before it can be implemented into the terraform-modules
